### ISSUE TITLE
Image does not respond to ACPI Shutdown

### ISSUE THREAD

**Issue by mikldt** [concerto/concerto-player#10]
It seems the only way to shut down the image (at least when running in virtual box) is to a hard reset / "Power Off". Not sure if this is a feature or a bug.

Using VirtualBox, with the concerto player image downloaded from  http://dl.concerto-signage.org/concerto.vdi 2013-08-24.

**Comment by augustf** [comment]
Sending the shutdown signal worked for me in the latest built without incident.

**Comment by maxencefrenette** [comment]
I am having the same problem with this image : http://dl.concerto-signage.org/concerto_player.vmdk . It happens consistently, even with a fresh image. Can anyone reproduce it ?

**Comment by asquared** [comment]
It should be noted that the risk of filesystem corruption from hard
powering down the players is minimal. The vast majority of the system is
read-only with writes going to ramdisk. Writes to persistent storage only
occur when configuration parameters are changed.

-Andrew
