### ISSUE TITLE
Make sure bandshelld_boot runs before sshd

### ISSUE THREAD

**Issue by augustf** [concerto/concerto-player#25]
As @asquared points out in https://github.com/concerto/bandshell/commit/672f1282e1bcccbb5ab3f81979856720790a4af0#commitcomment-11891694 , bandshelld_boot (which manages the password changes) should run before sshd to prevent an attack vector involving someone using the default ssh password before bandshell can change it.

**Comment by augustf** [comment]
@asquared Normally, to accomplish this, I would probably change /etc/init.d/ssh and run update-rc.d to accomplish this. What's the proper thing to do on a live image like this?

**Comment by asquared** [comment]
It may well already happen because /etc/init.d/concerto-live already had X-Start-Before: $network and the network is a requirement for ssh. In any case this should prevent any kind of attack via the network, since the passwords will be set before the network comes up.
