### ISSUE TITLE
Extra bars appear in Chromium

### ISSUE THREAD

**Issue by mastodon** [concerto/concerto-player#28]
chroot_tasks.sh should be updated to disable translation and crash bubbles for chromium.

Just add --disable-translate and --disable-infobars to chromium-browser line to prevent obstucting the content.

**Comment by augustf** [comment]
@asquared Do these seem like good flags to add to chroot_tasks?

**Comment by asquared** [comment]
I'll look into this after finishing up the UEFI build script. I don't see any harm in adding them but I also don't see an immediate need to change this.

**Comment by mastodon** [comment]
I ran into the translation popup when using non-english RSS feeds; the
disabling of infobars should prevent the yellow bars from reporting about
crashes when the the shutdown isn't a clean one.

**Comment by asquared** [comment]
Thanks for the instructions to reproduce. I'll take care of this shortly.

**Comment by augustf** [comment]
I just ran into the translation issue on the Concerto demo site. There was some French content in one of my screen's feeds and the chrome prompt wouldn't go away without clicking.
