### ISSUE TITLE
Ensure system time is correct

### ISSUE THREAD

**Issue by mikldt** [concerto/concerto-player#30]
We're having issues with screen on/off scheduling because the system time on many boxes is not correct. I think the issue is twofold: the system does not know the current time, and the system does not know the correct time zone.

I'm going to work on fetching the timezone, to be specified per-screen in Concerto, with bandshell (concerto/bandshell#45).

As for getting the time, I assume that this could be accomplished with NTP, but I'll make this a solution-agnostic ticket.

@asquared, does this sound like a reasonable addition to the player?

**Comment by augustf** [comment]
I think we already have ntpdate installed on the image.

**Comment by mikldt** [comment]
Ok, ntpdate was missing from the 0.9.0 version linked from the README. 0.9.2 appears to be better.

I'm not too familiar with the inner workings of ntpdate. It seems to have set the time correctly on my player. Interestingly, the ntpdate shell command does not look happy:

     9 Nov 02:56:12 ntpdate[2878]: no servers can be used, exiting


However, syslog makes it looks like the time was set at boot. I'm going to assume that's good enough, and just focus on getting the timezone right via bandshell.

**Comment by augustf** [comment]
I believe it takes as its required argument the server name of an NTP server like time.nist.gov or somesuch.
